CCOMP = gcc
OPT = -g -O0

SOURCE_2_2 = pub_sym_2_2.c

OUT_2_2 = pub2_2.out

$(OUT_2_2): $(SOURCE_2_2)
	$(CCOMP) $(SOURCE_2_2) $(OPT) -o $(OUT_2_2)

clean:
	rm $(OUT_1_1) $(OUT_1_2) $(OUT_2_1) $(OUT_2_2) $(OUT_1_1b)